import { getUseCaseAvgMaturity, getBlockCategory } from './maturity';

export function suggestPhase(useCase) {
  const maturity = getUseCaseAvgMaturity(useCase);
  if (maturity >= 3.8 && useCase.activityType === 'Support') return 'quickWins';
  if (maturity >= 3.5) return 'quickWins';
  if (maturity >= 2.5) return 'mediumTerm';
  return 'strategic';
}

export function computePhaseBlocks(useCases) {
  const blocks = new Set();
  useCases.forEach(uc => uc.buildingBlocks.forEach(b => blocks.add(b)));
  return [...blocks];
}

export function findDependencies(useCase, allSelected) {
  const deps = [];
  allSelected.forEach(other => {
    if (other.name === useCase.name) return;
    const shared = useCase.buildingBlocks.filter(b => other.buildingBlocks.includes(b));
    if (shared.length >= 3) {
      deps.push({ useCase: other, sharedBlocks: shared, count: shared.length });
    }
  });
  return deps.sort((a, b) => b.count - a.count);
}

export function generateRoadmapText(phases, shortlist) {
  const lines = ['# AI Implementation Roadmap', '', `Generated: ${new Date().toLocaleDateString()}`, ''];
  const phaseLabels = { quickWins: 'Quick Wins (0-3 months)', mediumTerm: 'Medium Term (3-12 months)', strategic: 'Strategic (12+ months)' };

  Object.entries(phaseLabels).forEach(([phaseId, label]) => {
    const items = shortlist.filter(item => item.phase === phaseId);
    if (!items.length) return;
    lines.push(`## ${label}`, '');
    items.forEach(item => {
      const maturity = getUseCaseAvgMaturity(item.useCase);
      lines.push(`- **${item.useCase.name}** (${item.useCase.valueChainArea}) — Maturity: ${maturity.toFixed(1)}`);
      lines.push(`  Building Blocks: ${item.useCase.buildingBlocks.join(', ')}`);
    });
    const allBlocks = computePhaseBlocks(items.map(i => i.useCase));
    lines.push('', `Required Building Blocks: ${allBlocks.length} unique capabilities`, '');
  });

  lines.push('---', 'Generated by AI Building Blocks Framework — MMG Management Consulting');
  return lines.join('\n');
}
