import { getUseCaseAvgMaturity } from './maturity';
import { computeReadinessScore, computeDimensionScores } from './assessment';
import { READINESS_DIMENSIONS } from '../data/constants';

export function computeQuadrant(impact, feasibility) {
  if (impact >= 3 && feasibility >= 3) return 'doFirst';
  if (impact >= 3 && feasibility < 3) return 'plan';
  if (impact < 3 && feasibility >= 3) return 'delegate';
  return 'reconsider';
}

export function getQuadrantLabel(quadrant) {
  const labels = {
    doFirst: 'Do First',
    plan: 'Plan Carefully',
    delegate: 'Delegate / Quick Task',
    reconsider: 'Reconsider',
  };
  return labels[quadrant] || quadrant;
}

export function getQuadrantColor(quadrant) {
  const colors = {
    doFirst: '#50D8A8',
    plan: '#FBB740',
    delegate: '#5BC8D4',
    reconsider: '#8E8E93',
  };
  return colors[quadrant] || '#8E8E93';
}

export function generateWorkshopReport(workshopName, assessment, priorities, roadmapShortlist) {
  const lines = [
    `# ${workshopName || 'AI Strategy Workshop'}`,
    '',
    `**Date**: ${new Date().toLocaleDateString()}`,
    '',
    '---',
    '',
    '## 1. Organization Readiness',
    '',
  ];

  if (assessment?.isComplete) {
    const score = computeReadinessScore(assessment.readinessRatings);
    lines.push(`**Overall Readiness Score**: ${score.toFixed(1)} / 5.0`, '');
    const dimScores = computeDimensionScores(assessment.readinessRatings);
    READINESS_DIMENSIONS.forEach(dim => {
      const val = dimScores[dim.id] ?? 0;
      lines.push(`- ${dim.label}: ${val.toFixed(1)}/5`);
    });
    lines.push('', '**Assessed Areas**:', '');
    assessment.selectedAreas.forEach(area => {
      const rating = assessment.areaRatings[area] || 1;
      lines.push(`- ${area}: Level ${rating}/5`);
    });
  } else {
    lines.push('*Assessment not completed*');
  }

  lines.push('', '---', '', '## 2. Prioritized Use Cases', '');

  const prioritized = Object.entries(priorities).map(([name, { impact, feasibility }]) => ({
    name, impact, feasibility, quadrant: computeQuadrant(impact, feasibility),
  }));

  const sorted = prioritized.sort((a, b) => (b.impact + b.feasibility) - (a.impact + a.feasibility));

  if (sorted.length > 0) {
    lines.push('| Use Case | Impact | Feasibility | Quadrant |');
    lines.push('|----------|--------|-------------|----------|');
    sorted.forEach(p => {
      lines.push(`| ${p.name} | ${p.impact}/5 | ${p.feasibility}/5 | ${getQuadrantLabel(p.quadrant)} |`);
    });
  } else {
    lines.push('*No use cases prioritized*');
  }

  lines.push('', '---', '', '## 3. Implementation Roadmap', '');

  if (roadmapShortlist?.length > 0) {
    const phases = { quickWins: [], mediumTerm: [], strategic: [] };
    roadmapShortlist.forEach(item => {
      if (phases[item.phase]) phases[item.phase].push(item);
    });

    const phaseLabels = {
      quickWins: 'Quick Wins (0-3 months)',
      mediumTerm: 'Medium Term (3-12 months)',
      strategic: 'Strategic (12+ months)',
    };

    Object.entries(phaseLabels).forEach(([id, label]) => {
      if (phases[id].length === 0) return;
      lines.push(`### ${label}`, '');
      phases[id].forEach(item => {
        const maturity = getUseCaseAvgMaturity(item.useCase);
        lines.push(`- **${item.useCase.name}** — Maturity: ${maturity.toFixed(1)}`);
      });
      lines.push('');
    });
  } else {
    lines.push('*No roadmap items*');
  }

  lines.push('---', '', `*Generated by AI Building Blocks Framework — MMG Management Consulting*`);
  return lines.join('\n');
}
